In [2]:
import numpy as np

In [3]:
data_file='/content/makeSenseOfCensus.csv'

In [12]:
data = np.genfromtxt(data_file, delimiter=",",skip_header=1)

# printing the data

print("\nData: \n\n", data)

print("\nType of data: \n\n", type(data))

#step 2 Append 'new_record' (given) to 'data' using "np.concatenate()"¶
new_record = [[50,9,4,1,0,0,40,0]]
new_data = np.concatenate((data,new_record),axis=0)
print(new_data)





Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


**step** 3 Check if it's a young country or old country

In [37]:


age = np.array(new_data[:,0], dtype='int64')
print(age)


[39 50 38 ... 40 39 50]


In [29]:
max_age= age.max()
print(max_age)

90


In [30]:
min_age= age.min()
print(min_age)

17


In [34]:
age_mean = age.mean()
print(age_mean)

38.06293706293706


In [35]:
age_std= np.std(age)
print(age_std)

13.341478176165857


Step 4: Let's check the country's race distribution to identify the **minorities**

In [50]:
Race= np.array(new_data[:,2], dtype='int64')
print(Race)
print(len(Race))


[4 4 4 ... 4 4 4]
1001


In [62]:
race_0=new_data[Race==0]
race_1=new_data[Race==1]
race_2=new_data[Race==2]
race_3=new_data[Race==3]
race_4=new_data[Race==4]


In [66]:
race_0

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

In [ ]:
race_1

In [70]:
race_2
race_3
race_4

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [80]:
len_0=len(race_0)
print(len_0)
len_1=len(race_1)
print(len_1)
len_2=len(race_2)
print(len_2)
len_3=len(race_3)
print(len_3)
len_4=len(race_4)
print(len_4)

10
27
110
6
848


In [83]:
min_num_citizens= min(len_0,len_1,len_2,len_3,len_4)
print("Race with the minimum no. of citizens is ",min_num_citizens)

Race with the minimum no. of citizens is  6


Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in **place**

In [111]:
age=new_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [115]:
senior_citizens = new_data[age>60] 
senior_citizens_len=len(senior_citizens)
senior_citizens_len


61

In [119]:
working_hours_sum =np.sum(senior_citizens[:,6])
print(working_hours_sum)

1917.0


In [121]:
avg_working_hours = np.divide(working_hours_sum,senior_citizens_len)
print(int(avg_working_hours))

31


**The policy is not in place because the average working hours > 25**

Step 6: Let's check that higher educated people have better pay in general.**bold text**

In [106]:
high = new_data[new_data[:,1]>10] #?????????
print(high)
print('------')
low= new_data[new_data[:,1]<=10]
print(low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
------
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


In [107]:
avg_pay_high =high[:,7]
print(avg_pay_high.mean())
avg_pay_low = low[:,7]
print(avg_pay_low.mean())

0.42813455657492355
0.13649851632047477
